# Generated by Django 5.0.3 on 2024-04-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccessManagementSystem', '0002_alter_accesslevel_enviroment_and_more'),
        ('LabManagementProcess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание документа')),
                ('document', models.FileField(upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='TypeConsumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа расходника')),
            ],
            options={
                'verbose_name': 'Тип расходника',
                'verbose_name_plural': 'Типы расходников',
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа оборудования')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание поля действия')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название расходника')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание расходника')),
                ('production_date', models.DateField(null=True, verbose_name='Дата изготовления')),
                ('storage_life', models.DateField(null=True, verbose_name='Срок годности')),
                ('amount', models.FloatField(blank=True, verbose_name='Остаток')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='LabManagementProcess.storagelocation', verbose_name='Местоположение')),
                ('usage_rights', models.ManyToManyField(blank=True, related_name='rights_consumables', to='AccessManagementSystem.role')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumables', to='ResourceInventory.typeconsumables', verbose_name='Тип расходника')),
            ],
            options={
                'verbose_name': 'Расходник',
                'verbose_name_plural': 'Расходники',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название оборудования')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание оборудования')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='LabManagementProcess.storagelocation', verbose_name='Местоположение')),
                ('usage_rights', models.ManyToManyField(blank=True, related_name='rights_equipments', to='AccessManagementSystem.role')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='ResourceInventory.typeequipment', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудования',
            },
        ),
        migrations.CreateModel(
            name='ActionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поля действия')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание поля действия')),
                ('consumables', models.ManyToManyField(blank=True, related_name='action_fields', to='ResourceInventory.consumables')),
                ('equipments', models.ManyToManyField(blank=True, related_name='action_fields', to='ResourceInventory.equipment')),
            ],
            options={
                'verbose_name': 'Поле действия',
                'verbose_name_plural': 'Поля действия',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название поля действия')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание поля действия')),
                ('action_fields', models.ManyToManyField(blank=True, related_name='procedure_templates', to='ResourceInventory.actionfield')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_templates', to='AccessManagementSystem.enviroment', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Шаблон методики',
                'verbose_name_plural': 'Шаблоны методик',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название анализа')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание анализа')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата рождения пользователя')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='AccessManagementSystem.enviroment', verbose_name='Автор')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='ResourceInventory.proceduretemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Методика',
                'verbose_name_plural': 'Методики',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название образца')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание образца')),
                ('production_date', models.DateField(null=True, verbose_name='Дата изготовления')),
                ('amount', models.FloatField(blank=True, verbose_name='Остаток')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='AccessManagementSystem.profile', verbose_name='Автор')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='ResourceInventory.procedure', verbose_name='Методика')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='AccessManagementSystem.project', verbose_name='Проект')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='LabManagementProcess.storagelocation', verbose_name='Местоположение')),
                ('usage_rights', models.ManyToManyField(blank=True, related_name='samples', to='AccessManagementSystem.role')),
            ],
            options={
                'verbose_name': 'Образец',
                'verbose_name_plural': 'Образцы',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название анализа')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание анализа')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis', to='AccessManagementSystem.profile', verbose_name='Исполнитель')),
                ('consumables', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis', to='ResourceInventory.consumables', verbose_name='Расходник')),
                ('documents', models.ManyToManyField(blank=True, related_name='analysis', to='ResourceInventory.document')),
                ('equipments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis', to='ResourceInventory.equipment', verbose_name='Оборудование')),
                ('sample', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis', to='ResourceInventory.sample', verbose_name='Образец')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
    ]
