# Generated by Django 5.0.3 on 2024-04-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccessManagementSystem', '0002_alter_accesslevel_enviroment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название лаборатории')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание лаборатории')),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labs', to='AccessManagementSystem.enviroment', verbose_name='Окружение')),
                ('profiles', models.ManyToManyField(blank=True, related_name='labs', to='AccessManagementSystem.profile')),
            ],
            options={
                'verbose_name': 'Лаборатория',
                'verbose_name_plural': 'Лаборатории',
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_locations', to='LabManagementProcess.lab', verbose_name='Лаборатория')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
