# Generated by Django 5.0.3 on 2024-04-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccessManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslevel',
            name='enviroment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_levels', to='AccessManagementSystem.enviroment', verbose_name='Окружение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='AccessManagementSystem.profile', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='role',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='AccessManagementSystem.accesslevel', verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='role',
            name='enviroment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='AccessManagementSystem.enviroment', verbose_name='Окружение'),
        ),
    ]
